
# Pandas Alıştırmalar

In [2]:
import numpy as np
import seaborn as sns
import pandas as pd
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
#  Seaborn kütüphanesi içerisinden Titanic veri setini yukleyelim
df = sns.load_dataset("titanic")

In [ ]:
#  Titanic veri setindeki kadın ve erkek yolcuların sayısını bulunuz.

df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [ ]:
# Her bir sutuna ait unique değerlerin sayısını bulunuz.
df.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [ ]:
# pclass değişkeninin unique değerlerini bulunuz.
# df["pclass"].value_counts()
df["pclass"].nunique()

3

In [ ]:
# pclass ve parch değişkenlerinin unique değerlerinin sayısını bulunuz.
df[["pclass","parch"]].nunique()

pclass    3
parch     7
dtype: int64

In [ ]:
# embarked değişkeninin tipini kontrol ediniz. Tipini category olarak değiştiriniz. Tekrar tipini kontrol ediniz.
print("ilk değişken tipi: ",df["embarked"].dtype)
df["embarked"] = df["embarked"].astype("category")
print("son değişken tipi: ",df["embarked"].dtype)

ilk değişken tipi:  object
son değişken tipi:  category

In [ ]:
# embarked değeri C olanların tüm bilgelerini gösteriniz.

df[df["embarked"] == "C"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [ ]:
# embarked değeri S olmayanların tüm bilgelerini gösteriniz.

df[df["embarked"] != "C"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# Yaşı 30 dan küçük ve kadın olan yolcuların tüm bilgilerini gösteriniz.

df[(df["age"] < 30) & (df["sex"]=="female") ]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [ ]:
# Fare'i 500'den büyük veya yaşı 70 den büyük yolcuların bilgilerini gösteriniz.
df[ (df["fare"] > 500) | (df["age"] >70)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# Her bir değişkendeki boş değerlerin toplamını bulunuz.
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
# who değişkenini dataframe'den düşürün.
df.drop("who",axis=1,inplace=True)

In [15]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True

In [ ]:

# deck değişkenindeki boş değerleri deck değişkenin en çok tekrar eden değeri (mode) ile doldurunuz.

In [17]:
x = df["deck"].mode()[0]
df["deck"].fillna(x,inplace=True)

In [18]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,C,Southampton,no,True

In [ ]:
# age değikenindeki boş değerleri age değişkenin medyanı ile doldurun.
x = df["age"].median()
df["age"].fillna(x, inplace=True)
# df["age"].fillna(df["age"].median(), inplace=True)

In [ ]:

# survived değişkeninin Pclass ve Cinsiyet değişkenleri kırılımınında sum, count, mean değerlerini bulunuz.
df.groupby(["pclass","sex"]).agg({"survived":["sum","count","mean"]})

              survived
                   sum count      mean
pclass sex
1      female       91    94  0.968085
       male         45   122  0.368852
2      female       70    76  0.921053
       male         17   108  0.157407
3      female       72   144  0.500000
       male         47   347  0.135447

In [ ]:

# 30 yaşın altında olanlar 1, 30'a eşit ve üstünde olanlara 0 vericek bir fonksiyon yazınız.
# Yazdığınız fonksiyonu kullanarak titanik veri setinde age_flag adında bir değişken oluşturunuz oluşturunuz.
# (apply ve lambda yapılarını kullanınız)
# df.loc[df["age"] < 30, "age_flag"] = 1
# df.loc[df["age"] >= 30, "age_flag"] = 0
# df["age_flag"] = [ 1 if degisken < 30 else 0 for degisken in df["age"] ] ## 1. yol
df["age_flag"] = df["age"].apply(lambda x: 1 if x<30 else 0) ## 2. yol

In [22]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone,age_flag
0,0,3,male,22.0,1,0,7.2500,S,Third,True,C,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,False,C,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False,0
4,0,3,male,35.0,0,0,8.0500,S,Third,True,C,Southampton,no,True,0

In [ ]:

# Seaborn kütüphanesi içerisinden Tips veri setini tanımlayınız.
tips = sns.load_dataset("tips")
tips.head()
tips.shape

(244, 7)

In [24]:
tips.value_counts()

total_bill  tip    sex     smoker  day   time    size
13.00       2.00   Female  Yes     Thur  Lunch   2       2
3.07        1.00   Female  Yes     Sat   Dinner  1       1
22.23       5.00   Male    No      Sun   Dinner  2       1
20.69       2.45   Female  No      Sat   Dinner  4       1
            5.00   Male    No      Sun   Dinner  5       1
                                                        ..
15.53       3.00   Male    Yes     Sat   Dinner  2       1
15.69       1.50   Male    Yes     Sun   Dinner  2       1
            3.00   Male    Yes     Sat   Dinner  3       1
15.77       2.23   Female  No      Sat   Dinner  2       1
50.81       10.00  Male    Yes     Sat   Dinner  3       1
Length: 243, dtype: int64

In [ ]:

# Time değişkeninin kategorilerine (Dinner, Lunch) göre total_bill
# değerlerinin toplamını, min, max ve ortalamasını bulunuz.
tips.groupby(["time"]).agg({"total_bill":["min","max","mean"]})

       total_bill
              min    max       mean
time
Lunch        7.51  43.11  17.168676
Dinner       3.07  50.81  20.797159

In [ ]:

# Günlere ve time göre total_bill değerlerinin toplamını, min, max ve ortalamasını bulunuz.

tips.groupby(["day","time"]).agg({"total_bill":["sum","min","max","mean"]})

            total_bill
                   sum    min    max       mean
day  time
Thur Lunch     1077.55   7.51  43.11  17.664754
     Dinner      18.78  18.78  18.78  18.780000
Fri  Lunch       89.92   8.58  16.27  12.845714
     Dinner     235.96   5.75  40.17  19.663333
Sat  Lunch        0.00    NaN    NaN        NaN
     Dinner    1778.40   3.07  50.81  20.441379
Sun  Lunch        0.00    NaN    NaN        NaN
     Dinner    1627.16   7.25  48.17  21.410000

In [ ]:

# Lunch zamanına ve kadın müşterilere ait total_bill ve tip
# değerlerinin day'e göre toplamını, min, max ve ortalamasını bulunuz.
tips[(tips["sex"]=="Female") & (tips["time"]=="Lunch")].groupby(["day"]).agg({"total_bill":["sum","min","max","mean"],"tip":["sum","min","max","mean"]})

     total_bill                            tip
            sum    min    max      mean    sum   min   max      mean
day
Thur     516.11   8.35  43.11  16.64871  79.42  1.25  5.17  2.561935
Fri       55.76  10.09  16.27  13.94000  10.98  2.00  3.48  2.745000
Sat        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN
Sun        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN

In [ ]:

#  size'i 3'ten küçük, total_bill'i 10'dan büyük olan siparişlerin ortalaması nedir?
tips[ (tips["size"] < 3) & (tips["total_bill"] > 10)][["total_bill","tip","size"]].agg(["mean"])

      total_bill       tip      size
mean   17.184965  2.638811  1.993007

In [ ]:

# total_bill_tip_sum adında yeni bir değişken oluşturun.
# Her bir müşterinin ödediği totalbill ve tip in toplamını versin.
tips["total_bill_tip_sum"] = tips[["total_bill","tip"]].sum(axis=1)
tips.head()

   total_bill   tip     sex smoker  day    time  size  total_bill_tip_sum
0       16.99  1.01  Female     No  Sun  Dinner     2               18.00
1       10.34  1.66    Male     No  Sun  Dinner     3               12.00
2       21.01  3.50    Male     No  Sun  Dinner     3               24.51
3       23.68  3.31    Male     No  Sun  Dinner     2               26.99
4       24.59  3.61  Female     No  Sun  Dinner     4               28.20

In [ ]:

# Total_bill değişkeninin kadın ve erkek için ayrı ayrı ortalamasını bulun.
# Bulduğunuz ortalamaların altında olanlara 0, üstünde ve eşit olanlara bir verildiği
# yeni bir total_bill_flag değişkeni oluşturun.
# Dikkat !! Female olanlar için kadınlar için bulunan ortalama dikkate alıncak, male için ise erkekler için bulunan ortalama.
# parametre olarak cinsiyet ve total_bill alan bir fonksiyon yazarak başlayın. (If-else koşulları içerecek)

In [36]:
def ortalamaKontrol(gender, bill):
  female_avg = tips[tips["sex"]=="Female"]["total_bill"].mean()
  male_avg = tips[tips["sex"]=="Male"]["total_bill"].mean()
  if gender == "Female" :
    if bill >= female_avg:
      return 1
    else:
      return 0
  else:
    if bill >= male_avg:
      return 1
    else:
      return 0

In [ ]:

# total_bill_flag değişkenini kullanarak cinsiyetlere göre ortalamanın
# altında ve üstünde olanların sayısını gözlemleyin.
# tips.groupby(["sex","total_bill_flag"]).agg({"time":"count"})
pd.crosstab(tips["sex"],tips["total_bill_flag"])

total_bill_flag   0   1
sex
Male             95  62
Female           54  33

In [ ]:

# total_bill_tip_sum değişkenine göre büyükten küçüğe sıralayınız ve ilk 30 kişiyi yeni bir dataframe'e atayınız.
tips.head()

,total_bill,tip,sex,smoker,day,time,size,total_bill_tip_sum,total_bill_flag
0,16.99,1.01,Female,No,Sun,Dinner,2,18.00,0
1,10.34,1.66,Male,No,Sun,Dinner,3,12.00,0
2,21.01,3.50,Male,No,Sun,Dinner,3,24.51,1
3,23.68,3.31,Male,No,Sun,Dinner,2,26.99,1
4,24.59,3.61,Female,No,Sun,Dinner,4,28.20,1

In [47]:
tips_30 = tips.sort_values("total_bill_tip_sum",ascending=False).head(30)

In [48]:
tips_30

,total_bill,tip,sex,smoker,day,time,size,total_bill_tip_sum,total_bill_flag
170,50.81,10.00,Male,Yes,Sat,Dinner,3,60.81,1
212,48.33,9.00,Male,No,Sat,Dinner,4,57.33,1
59,48.27,6.73,Male,No,Sat,Dinner,4,55.00,1
156,48.17,5.00,Male,No,Sun,Dinner,6,53.17,1
182,45.35,3.50,Male,Yes,Sun,Dinner,3,48.85,1
197,43.11,5.00,Female,Yes,Thur,Lunch,4,48.11,1
23,39.42,7.58,Male,No,Sat,Dinner,4,47.00,1
102,44.30,2.50,Female,Yes,Sat,Dinner,3,46.80,1
142,41.19,5.00,Male,No,Thur,Lunch,5,46.19,1
95,40.17,4.73,Male,Yes,Fri,Dinner,4,44.90,1
184,40.55,3.00,Male,Yes,Sun,Dinner,2,43.55,1
112,38.07,4.00,Male,No,Sun,Dinner,3,42.07,1
207,38.73,3.00,Male,Yes,Sat,Dinner,4,41.73,1
56,38.01,3.00,Male,Yes,Sat,Dinner,4,41.01,1
141,34.30,6.70,Male,No,Thur,Lunch,6,41.00,1
238,35.83,4.67,Female,No,Sat,Dinner,3,40.50,1
11,35.26,5.00,Female,No,Sun,Dinner,4,40.26,1
52,34.81,5.20,Female,No,Sun,Dinner,4,40.01,1
85,34.83,5.17,Female,No,Thur,Lunch,4,40.00,1
47,32.40,6.00,Male,No,Sun,Dinner,4,38.40,1
180,34.65,3.68,Male,Yes,Sun,Dinner,4,38.33,1
179,34.63,3.55,Male,Yes,Sun,Dinner,2,38.18,1
83,32.68,5.00,Male,Yes,Thur,Lunch,2,37.68,1
39,31.27,5.00,Male,No,Sat,Dinner,3,36.27,1
167,31.71,4.50,Male,No,Sun,Dinner,4,36.21,1
175,32.90,3.11,Male,Yes,Sun,Dinner,2,36.01,1
44,30.40,5.60,Male,No,Sun,Dinner,4,36.00,1
173,31.85,3.18,Male,Yes,Sun,Dinner,2,35.03,1
116,29.93,5.07,Male,No,Sun,Dinner,4,35.00,1
155,29.85,5.14,Female,No,Sun,Dinner,5,34.99,1