# Temel Pandas Fonksiyonları

Son yıllarda dijitalleşen dünyanın sonucunda ortaya çıkan dijital uygulamalar birbirinden farklı veriler ortaya çıkardı. Ortaya çıkan bu verileri işleyebilmek eskisine göre çok daha önemli hale geldi. Dijitalleşme döneminden önce, birçok kurumsal yazılım firması kendi çalışanlarının operasyonel işlerini takip edebilmek amacıyla oluşturduğu finans, satış, müşteri verileri gibi verilerin işlenmesine odaklıydı. Günümüzde ise firmaların ürün ve servislerini kullanan kullanıcıların oluşturduğu verileri işlemek çok daha önemli hale geldi. Böylece müşterilere daha iyi hizmet sunmak ve ürün çeşitliliğini takip etmek açısından daha sağlıklı veriler elde edilebilirdi. Daha önceden yapısal bir veri tabanı yeterli olurken, bu dönemde yapısal olmayan verilerin işlenmesi ve anlamlandırılması için kullanılan araçlar ve çeşitlilikleri de gelişti. Dolayısıyla veri işlemek deyince akla gelen veri tabanı, veri işleme ve dönüştürme gibi araçların dışına çıkılarak Python gibi açık kodlu araçlar veri işlemede sıkça kullanılır oldu. 

Bu yazımızda Python’un veri işleme kütüphanesi olan pandas’ın temel fonksiyonlarına değinerek veri işlemeye giriş yapacağız.

Bir veri seti üzerinde temel istatistik analizi için kullanılacak temel fonksiyonlar: count(), first(), last(), mean(), median(), min(), max(), std(), var(), sum()

Veri seti (dataset) nedir? Veri seti; satırlarında gözlem birimleri, sütunlarında ise değişkenler bulunan iki boyutlu bir matristir. Satır ve sütunların kesişim bölgelerine 'hücre (cell)' adı verilir. Her bir hücreye, gözlemlerin değerleri yani yapılan ölçmenin sonuçları sayı veya sembol olarak girilir. Bir hücrede herhangi bir sayı veya sembol olmaması, amaçlanan gözlemin bulunmadığını ifade eder. Veri setinde yer alan bu tür boşluklar 'kayıp veri (missing value)' olarak adlandırılır.

Veri setlerini kendimiz excel ortamında da oluşturabiliriz. Ancak *python seaborn kutuphanesi* hazır veri setleri sunmakta ve hepimiz aynı veri üzerinde çalıştığımızda sonuçları değerlendirmek çok daha kolay olacaktır. Bu nedenle bu derste bu kütüphaneyi kullanacağız.

In [1]:
import seaborn as sns

In [2]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load a dataset from the online repository (requires internet).

Parameters
----------
name : str
    Name of the dataset (`name`.csv on
    https://github.com/mwaskom/seaborn-data).  You can obtain list of
    available datasets using :func:`get_dataset_names`
cache : boolean, optional
    If True, then cache data locally and use the cache on subsequent calls
data_home : string, optional
    The directory in which to cache data. By default, uses ~/seaborn-data/
kws : dict, optional
    Passed to pandas.read_csv
File:      /opt/anaconda3/lib/python3.7/site-packages/seaborn/utils.py
Type:      function

In [3]:
sns.get_dataset_names()

/opt/anaconda3/lib/python3.7/site-packages/seaborn/utils.py:384: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 384 of the file /opt/anaconda3/lib/python3.7/site-packages/seaborn/utils.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  gh_list = BeautifulSoup(http)

['anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'iris',
 'mpg',
 'planets',
 'tips',
 'titanic']

In [5]:
veri = sns.load_dataset("flights")

In [6]:
veri.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [7]:
veri.shape

(144, 3)

In [8]:
# ortalama fonksiyonu ele alalım

In [9]:
veri["passengers"].mean()

280.2986111111111

In [10]:
# yolcu sayısını bulalım

In [11]:
veri["passengers"].count()

144

In [31]:
# minimum yolcu sayısını bulalım

In [12]:
veri["passengers"].min()

104

In [34]:
# maksimum yolcu sayısını bulalım

In [13]:
veri["passengers"].max()

622

In [36]:
# yolcu toplamını bulalım

In [14]:
veri["passengers"].sum()

40363

In [15]:
# standart sapma hesaplayalım

Standart sapma bir dağılım ölçüsüdür. Standart sapma, veriler hakkında tahminler yapmamızı sağlar. Verilerin ortalamadan ne kadar saptıklarını ifade etmek için kullanılır. Aynı zamanda varyansın da kare köküdür. Bir dizideki verilerin değerleri ortalamaya yakınsa standart sapma küçüktür. Ama verilerin değerleri ortalamadan uzaksa standart sapma büyük olur. Eğer bütün veri değerleri birbirine eşitse standart sapma aritmetik ortalamaya eşit olur.

In [16]:
veri["passengers"].std()

119.96631694294321

In [17]:
# varyansını hesaplayalım

In [18]:
veri["passengers"].var()

14391.917200854701

In [19]:
# Bütün bu istatiksel bilgileri tek bir fonksiyonla öğrenebiliriz

In [20]:
veri.describe()

              year  passengers
count   144.000000  144.000000
mean   1954.500000  280.298611
std       3.464102  119.966317
min    1949.000000  104.000000
25%    1951.750000  180.000000
50%    1954.500000  265.500000
75%    1957.250000  360.500000
max    1960.000000  622.000000

In [21]:
# satır sutun yerlerini değişmek istersek transpoze alabiliriz

In [22]:
veri.describe().T

,count,mean,std,min,25%,50%,75%,max
year,144.0,1954.500000,3.464102,1949.0,1951.75,1954.5,1957.25,1960.0
passengers,144.0,280.298611,119.966317,104.0,180.00,265.5,360.50,622.0

In [23]:
# iris veri setine bakalım

In [24]:
veri_iris = sns.load_dataset("iris")

In [25]:
veri_iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [27]:
veri_iris.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [29]:
veri_iris.shape

(150, 5)

In [30]:
veri_iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000